site_name: Practical Web Programming
site_url: https://pwp.stevecassidy.net/
nav:
  - 'index.md'
  - 'about.md'
theme: 
  name: bootstrap4
  custom_dir: custom_theme
dev_addr: localhost:8109
plugins:
  - search
