# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 16.10
          
      # build 
      - name: Run a multi-line script
        run: npm ci
      - run: npm run build

      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .retype/
          remote_path: webapps/pwp/
          remote_host: stevecassidy.net
          remote_user: steve
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}